version: '3'

services:

  db:
    image: postgres
    container_name: local_pgdb
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PGDATA: /data/postgres
    volumes:
     - mydata:/var/lib/postgresql/data
     
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

      
volumes:
  mydata:
    driver: local
  pgadmin-data:
  grafana-data: