services:

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.app
    container_name: app
    restart: always
    env_file:
      - ../config/.env
    ports:
    - "8000:8000"
    networks:
      - db_network

  postgres-db:
    build: 
        context: ../
        dockerfile: ./docker/Dockerfile
    container_name: db
    restart: always
    env_file:
      - ../config/.env
    ports:
    - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db_network

  fastapi-auth:
    build: 
        context: ../auth
        dockerfile: Dockerfile
    container_name: auth
    restart: always
    env_file:
      - ../config/.env
    ports:
    - "8001:8001"
    networks:
      - db_network

volumes:
  pg_data:

networks:
  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
     