services:
  postgres_test:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.testdb
    container_name: postgres_test
    restart: always
    env_file:
      - ../config/.env.test
    ports:
      - "5432:5432"