services:
  postgres_test:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.testdb
    container_name: postgres_test
    restart: always
    env_file:
      - .env.test
    ports:
      - "5433:5432"