[project]
name = "auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "passlib>=1.7.4",
    "pydantic>=2.10.6",
    "pyjwt>=2.10.1",
    "uvicorn>=0.34.0",
]
